### ISSUE TITLE
How do we signal data being loaded?

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/website-ui-specs#5]
We need to establish a site-wide standard for signaling that data is being loaded into the page. This applies to page-load data loading (like populating the gene search selectors) as well as search results. No reason to have different behavior, data loading is data loading.

 From @alancleary : 

> I still need clarification on the behavior of the "Loading form data"/"Form data loaded element", i.e. do we want it to 
> be an alert or will just a spinner do. If we go for the alert, do we want it to close automatically? And if so, should 
> that happen immediately after the form data is loaded or should there be a pause so users will see that the load was 
> successful. Currently you can close it using the close "X" button on the right.

So here's a list of options, chime in @alancleary @adf-ncgr @cann0010 @ctcncgr  @jd-campbell and myself:
- loading spinner, vanishes after data loaded [**Sam**, **Andrew]**
- alert (text box with words) that closes automatically after data loaded
- alert (text box with words) that closes after a standard delay after data loaded [**Alan**]
- alert (text box with words) that persists until user closes it using an X button

Abstention: **Steven**

**Comment by sammyjava** [comment]
I vote for a standard spinner that vanishes after data load. I'll be happy to find a list of spinners from which to choose the official one.

**Comment by alancleary** [comment]
I think alerts are the way to go because we can add contextual information, such as what type of data is being loaded or what happened if there aren't any results, i.e. no results were found or something went wrong. Since we want this to be consistent it might make sense to use formatted strings for the messages so they can be context specific. For example, `` `Loading ${dataType}` `` and `` `Successfully loaded ${dataType}` ``.

I like the idea of the alerts automatically closing after a successful load, perhaps after a brief pause to show a success message just so if the user is watching the loading alert doesn't just disappear without any indication of "exit status". This means the success message probably shouldn't contain any new information, like how much data was loaded.

Regarding the spinner, in general I think we should use whatever we can from UIkit for stylistic consistency, so here it would be UIkit's [Spinner element](https://getuikit.com/docs/spinner) which draws the spinner as an SVG that can be scaled to arbitrary size.

**Edit:** So my vote is "alert (text box with words) that closes after a standard delay after data loaded"

**Comment by sammyjava** [comment]
> Regarding the spinner, in general I think we should use whatever we can from UIkit for stylistic consistency, so here it would be UIkit's [Spinner element](https://getuikit.com/docs/spinner) which draws the spinner as an SVG that can be scaled to arbitrary size.

Thumbs up on that if we choose to use a spinner.

**Comment by adf-ncgr** [comment]
I'd vote for a spinner while waiting for query response to be returned and an alert if no data is returned (either because a query produces no results or else an error condition). I don't think a successful query response with data needs further commentary.

**Comment by StevenCannon-USDA** [comment]
I trust you guys. Low-information voter here with respect to "alert options."
(Btw, cann0010 has become StevenCannon-USDA, due to changes afoot with USDA GitHub activity.)

**Comment by sammyjava** [comment]
> I'd vote for a spinner while waiting for query response to be returned and an alert if no data is returned (either because a query produces no results or else an error condition). I don't think a successful query response with data needs further commentary.

The no-data-returned is handled by a "0 results found" text box, not a temporary alert. I think that's what you want. So I'll say you vote for the loading spinner while data is being requested. But the no-data-returned response is, I suppose, something we should standardize as well. I don't think that's very controversial.

![image](https://user-images.githubusercontent.com/5657219/234592186-75ee5cee-eb88-4dbf-8d4f-6ceed3d5f476.png)

**Comment by adf-ncgr** [comment]
OK, thanks- any reason not to just use the same text box for error messages?

**Comment by sammyjava** [comment]
> OK, thanks- any reason not to just use the same text box for error messages?

This issue isn't about error messages. :)

**Comment by alancleary** [comment]
It sounds like we're leaning towards a spinner with no alert when loading data and only showing an alert with a message when no data is loaded. Any opinions on where this spinner should go in the UI, its size, etc? Having it in place of the alert above the element it corresponds to would be easiest to implement. Covering the part of the page where the content will go once it's loaded with a semiopaque color and a spinner in the middle is an approach I've noticed on websites in general.

**Comment by alancleary** [comment]
OK, I've implemented a loading component that provides a spinner overlay when loading data and shows alerts when no results are loaded. The code is in the [loading-element-prototype](https://github.com/legumeinfo/web-components/tree/loading-element-prototype) branch of the web-components repo. Here's a screenshot showing an example of a spinner being overlaid on the gene search form while the data for its selectors is loading. Similarly,  a spinner is being overlaid on the search results as if the user had triggered a new search or clicked the next/previous page button.

![Screenshot 2023-04-26 at 12-18-05 LIS Web-Components - lis-gene-search-element lis-linkout-element and lis-modal-element](https://user-images.githubusercontent.com/836063/234667142-caaa2ed9-733e-43f2-b67e-3b0870bcfc01.png)

If a spinner's load event fails or no data is loaded, then an alert will be shown, like what the components are already doing, but I've the loading component uses generic messages. Here's an example where the gene search form's data failed to load and no results were found for a search:

![Screenshot 2023-04-26 at 12-25-49 LIS Web-Components - lis-gene-search-element lis-linkout-element and lis-modal-element](https://user-images.githubusercontent.com/836063/234669005-fedd5392-cd61-4a83-b6fe-d95655b56ba1.png)

Let me know what you think.

**Comment by adf-ncgr** [comment]
works for me, thanks

**Comment by alancleary** [comment]
Last call for input on the loading component I prototyped. If it's not shot down by tomorrow then it's getting merged.

**Comment by sammyjava** [comment]
I like it. I like the fade on the previous results while it's pulling new results as well!

**Comment by alancleary** [comment]
This has been implemented for a while, and a draft spec has finally been added: issue #17. Please continue the conversation there if necessary. Closing
